[colors]
ansi = [
    "#010409",
    "#e34944",
    "#71d66e",
    "#dbd07b",
    "#4480d3",
    "#5b89bf",
    "#58a6ff",
    "#abb2bf",
]
background = "#010409"
brights = [
    "#5c6370",
    "#e05f60",
    "#88e086",
    "#e8df97",
    "#a7d6ff",
    "#3b7da4",
    "#5b76b0",
    "#ffffff",
]
cursor_bg = "#58a6ff"
cursor_border = "#58a6ff"
cursor_fg = "#010409"
foreground = "#c9d1d9"
selection_bg = "#388bfd"
selection_fg = "#c9d1d9"

[metadata]
author = "thrillho93"
name = "GitHub Dark"
