[colors]
ansi = [
    "#3A2E25",
    "#AD4433",
    "#6B8050",
    "#BD8838",
    "#B85A30",
    "#9A6860",
    "#A07058",
    "#6A5D51",
]
background = "#F2E8D8"
brights = [
    "#9B8D7F",
    "#AD4433",
    "#6B8050",
    "#BD8838",
    "#A04D28",
    "#9A6860",
    "#A07058",
    "#3A2E25",
]
cursor_bg = "#B85A30"
cursor_border = "#B85A30"
cursor_fg = "#FFFCF8"
foreground = "#3A2E25"
selection_bg = "#9B8D7F"
selection_fg = "#FFFCF8"

[colors.indexed]

[metadata]
name = "Oxide Light"
